name: quizz
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  youtube_player_flutter: ^8.0.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  random_string: ^2.3.1
  camera: ^0.11.0
  image: ^4.1.7
  image_picker: ^1.1.1
  cached_network_image: ^3.3.1
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.0.0
  share_plus: ^10.1.1
  intl: ^0.19.0
  sqflite: ^2.4.0
  path: ^1.9.0
  http: ^1.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    #  - assets/john.jpg
    # - assets/sarah.jpg
    # - assets/michael.jpg
    # - assets/emily.jpg
    # - assets/david.jpg
    # - assets/alice.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
